---
- name: create resource group {{ instance_name }}
  azure_rm_resourcegroup:
      name: "{{ instance_name }}"
      location: "{{ azure_location }}"
      state: present

- name: create virtual network {{ instance_name }}
  azure_rm_virtualnetwork:
      resource_group: "{{ instance_name }}"
      name: "{{ instance_name }}"
      address_prefixes_cidr: "10.1.0.0/16"
      state: present

- name: create a subnet {{ instance_name }}
  azure_rm_subnet:
    resource_group: "{{ instance_name }}"
    virtual_network_name: "{{ instance_name }}"
    name: "{{ instance_name }}"
    address_prefix_cidr: "10.1.0.0/24"

- name: create virtual machine {{ instance_name }}
  azure_rm_virtualmachine:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    vm_size: "{{ instance_flavor}}"
    managed_disk_type: Premium_LRS
    admin_username: azure
    virtual_network_name: "{{ instance_name }}"
    ssh_password_enabled: false
    ssh_public_keys:
    - path: /home/azure/.ssh/authorized_keys
      key_data: "{{ azure_ssh_public_key }}"
    image:
      offer: RHEL
      publisher: RedHat
      sku: 8-lvm-gen2
      version: latest
    state: present
