---
- name: collect facts for existing virtual machine
  azure_rm_virtualmachine_info:
    name: "{{ instance_name }}"
    resource_group: "{{ instance_name }}"
  register: vm

- name: remove DNS record
  include_role:
    name: nsupdate
  vars:
    ipaddress: "{{ vm.ansible_facts.azure_vm.properties. networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    instance_name: "{{ instance_name }}"
    keyfile: "{{ dns_keyfile }}"
    suffix: "{{ dns_suffix }}"
    mode: remove
  when: vm is defined

- name: remove virtual machine {{ instance_name }}
  azure_rm_virtualmachine:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    admin_username: azure
    state: absent

- name: remove network interface of VM {{ instance_name }}
  azure_rm_networkinterface:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    subnet_name: "{{ instance_name }}"
    virtual_network: "{{ instance_name }}"
    state: absent

- name: remove subnet {{ instance_name }}
  azure_rm_subnet:
    resource_group: "{{ instance_name }}"
    virtual_network_name: "{{ instance_name }}"
    name: "{{ instance_name }}"
    state: absent

- name: remove virtual network {{ instance_name }}
  azure_rm_virtualnetwork:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    state: absent

- name: remove resource group {{ instance_name }} and all associated resources
  azure_rm_resourcegroup:
    name: "{{ instance_name }}"
    state: absent
    force_delete_nonempty: true
