---
- name: unregister {{ instance_name }} from RHN if reachable
  ansible.builtin.command:
    cmd: 'ssh ansible@{{ instance_name }}.{{ dns_suffix }}.ansible-labs.de "sudo subscription-manager unregister"'
  when:
    - instance_name is defined
    - dns_suffix is defined
  ignore_errors: true

- name: remove DNS record
  include_role:
    name: nsupdate
  vars:
    shortname: "{{ instance_name }}"
    keyfile: "{{ dns_keyfile }}"
    suffix: "{{ dns_suffix }}"
    mode: remove
  when:
    - dns_update | bool

- name: remove virtual machine {{ instance_name }}
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    admin_username: azure
    state: absent
  ignore_errors: true

- name: remove network interface of VM {{ instance_name }}
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    subnet_name: "{{ instance_name }}"
    virtual_network: "{{ instance_name }}"
    state: absent
  ignore_errors: true

- name: remove subnet {{ instance_name }}
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ instance_name }}"
    virtual_network_name: "{{ instance_name }}"
    name: "{{ instance_name }}"
    state: absent
  ignore_errors: true

- name: remove virtual network {{ instance_name }}
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    state: absent
  ignore_errors: true

- name: remove resource group {{ instance_name }} and all associated resources - this can take a minute
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ instance_name }}"
    state: absent
    force_delete_nonempty: true
