---
- name: remove virtual machine {{ instance_name }}
  azure_rm_virtualmachine:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    admin_username: azure
    state: absent

- name: remove network interface of VM {{ instance_name }}
  azure_rm_networkinterface:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    subnet_name: "{{ instance_name }}"
    virtual_network: "{{ instance_name }}"
    state: absent

- name: remove subnet {{ instance_name }}
  azure_rm_subnet:
    resource_group: "{{ instance_name }}"
    virtual_network_name: "{{ instance_name }}"
    name: "{{ instance_name }}"
    state: absent

- name: remove virtual network {{ instance_name }}
  azure_rm_virtualnetwork:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    state: absent

- name: remove resource group {{ instance_name }} and all associated resources
  azure_rm_resourcegroup:
    name: "{{ instance_name }}"
    state: absent
    force_delete_nonempty: true
