---
- name: create resource group {{ instance_name }}
  azure_rm_resourcegroup:
    name: "{{ instance_name }}"
    location: "{{ azure_location }}"
    state: present

- name: create virtual network {{ instance_name }}
  azure_rm_virtualnetwork:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    address_prefixes_cidr: "10.1.0.0/16"
    state: present

- name: create subnet {{ instance_name }}
  azure_rm_subnet:
    resource_group: "{{ instance_name }}"
    virtual_network_name: "{{ instance_name }}"
    name: "{{ instance_name }}"
    address_prefix_cidr: "10.1.0.0/24"

- name: create virtual machine {{ instance_name }}
  azure_rm_virtualmachine:
    resource_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    vm_size: "{{ instance_flavor }}"
    managed_disk_type: Premium_LRS
    admin_username: ansible
    virtual_network_name: "{{ instance_name }}"
    open_ports:
    - 22
    - 80
    - 443
    ssh_password_enabled: false
    ssh_public_keys:
    - path: /home/ansible/.ssh/authorized_keys
      key_data: "{{ azure_ssh_public_key }}"
    image:
      offer: "{{ azure_image_offer }}"
      publisher: "{{ azure_image_publisher }}"
      sku: "{{ azure_image_sku }}"
      version: latest
    state: present
  register: vm

- name: update DNS record
  include_role:
    name: nsupdate
  vars:
    ipaddress: "{{ vm.ansible_facts.azure_vm.properties. networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    instance_name: "{{ instance_name }}"
    keyfile: "{{ dns_keyfile }}"
    suffix: "{{ dns_suffix }}"
    mode: update
  when: dns_update | bool