---
- name: Remove EC2 {{ ec2_os_type }} instance {{ instance_name }}
  community.aws.ec2_instance:
    name: "{{ instance_name }}"
    region: "{{ ec2_region }}"
    state: absent
- name: Remove EC2 security group {{ instance_name }}
  amazon.aws.ec2_group:
    name: "{{ instance_name }}"
    region: "{{ ec2_region }}"
    state: absent
