---
- debug: msg="{{ lookup('env','AWS_ACCESS_KEY_ID') }} is an environment variable"
  register: key

- debug:
    var: key

- debug: msg="{{ lookup('env','AWS_SECRET_ACCESS_KEY') }} is an environment variable"
  register: key

- debug:
    var: key

- name: create security group
  ec2_group:
    name: "{{ instance_name }}"
    description: HTTP, HTTPS and SSH
    # without the two following lines I received the error:
    # Error in describe_security_groups: Unable to locate credentials
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    state: present
    rules:
    - proto: tcp
      ports:
      - 80
      - 443
      - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all on port 80
    region: "{{ ec2_region }}"

- name: create EC2 instance
  ec2_instance:
    image_id: "{{ ec2_ami }}"
    instance_type: "{{ instance_flavor }}"
    security_group: "{{ instance_name }}"
    name: "{{ instance_name }}"
    key_name: "{{ ec2_keypair }}"
    region: "{{ ec2_region }}"
