---
- name: check if there is a DNS record
  shell: host {{ instance_name }}.{{ dns_suffix }}.ansible-labs.de
  changed_when: false
  register: lookup
  ignore_errors: true

- name: remove DNS record
  include_role:
    name: nsupdate
  vars:
    shortname: "{{ instance_name }}"
    keyfile: "{{ dns_keyfile }}"
    suffix: "{{ dns_suffix }}"
    mode: remove
  when:
  - lookup.rc == 0
  - dns_update | bool

- name: Gather subnet information
  amazon.aws.ec2_vpc_subnet_facts:
    filters:
      "tag:Name": "{{ instance_name }}"
  register: subnet

- name: Remove EC2 {{ ec2_os_type }} instance {{ instance_name }} - this can take a minute
  community.aws.ec2_instance:
    name: "{{ instance_name }}"
    region: "{{ ec2_region }}"
    vpc_subnet_id: "{{ subnet.subnets[0].subnet_id }}"
    state: absent
  when: subnet.subnets[0].subnet_id is defined

- name: Remove SSH Key pair
  amazon.aws.ec2_key:
    name: "{{ instance_name }}"
    state: absent

- name: Remove EC2 security group {{ instance_name }}
  amazon.aws.ec2_group:
    name: "{{ instance_name }}"
    region: "{{ ec2_region }}"
    state: absent

- name: Remove Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ subnet.subnets[0].vpc_id }}"
    state: absent
    cidr: "172.31.1.0/24"
  when: subnet.subnets[0].subnet_id is defined

- name: Gather Route Table information
  community.aws.ec2_vpc_route_table_facts:
    filters:
      "tag:Name": "{{ instance_name }}"
  register: route_table

- name: Gather VPC information
  amazon.aws.ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ instance_name }}"
  register: vpc

- name: Remove Route Table
  community.aws.ec2_vpc_route_table:
    route_table_id: "{{ route_table.route_tables[0].id }}"
    vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
    state: absent
    region: "{{ ec2_region }}"
    lookup: id
  when: route_table.route_tables[0].id is defined

- name: Remove internet gateway
  community.aws.ec2_vpc_igw:
    state: absent
    vpc_id: "{{ vpc.vpcs[0].vpc_id }}"

- name: Remove VPC {{ instance_name }}
  amazon.aws.ec2_vpc_net:
    name: "{{ instance_name }}"
    cidr_block: "172.31.0.0/16"
    state: absent
