---
- name: remove {{ instance_name }} instance
  gcp_compute_instance:
      state: absent
      name: "{{ instance_name }}"
      zone: "{{ gcp_zone }}"

- name: remove {{ instance_name }} disk
  gcp_compute_disk:
      name: "{{ instance_name }}-disk"
      state: absent
      zone: "{{ gcp_zone }}"

- name: remove {{ instance_name }} firewall for SSH, HTTP and HTTPS traffic
  gcp_compute_firewall:
      name: "{{ instance_name }}-firewall"
      state: absent

- name: remove {{ instance_name }} IP address
  gcp_compute_address:
      name: "{{ instance_name }}-address"
      state: absent
      region: "{{ gcp_region }}"

- name: remove {{ instance_name }} network
  gcp_compute_network:
      name: "{{ instance_name }}-network"
      state: absent
