---
- name: check if there is a DNS record
  shell: host {{ instance_name }}.{{ dns_suffix }}.ansible-labs.de
  changed_when: false
  register: lookup
  ignore_errors: true

- name: remove DNS record
  include_role:
    name: nsupdate
  vars:
    instance_name: "{{ instance_name }}"
    keyfile: "{{ dns_keyfile }}"
    suffix: "{{ dns_suffix }}"
    mode: remove
  when:
  - lookup.rc == 0
  - dns_update | bool

- name: remove {{ instance_name }} instance
  gcp_compute_instance:
      state: absent
      name: "{{ instance_name }}"
      zone: "{{ gcp_zone }}"

- name: remove {{ instance_name }} disk
  gcp_compute_disk:
      name: "{{ instance_name }}-disk"
      state: absent
      zone: "{{ gcp_zone }}"

- name: remove {{ instance_name }} firewall for SSH, HTTP and HTTPS traffic
  gcp_compute_firewall:
      name: "{{ instance_name }}-firewall"
      state: absent

- name: remove {{ instance_name }} IP address
  gcp_compute_address:
      name: "{{ instance_name }}-address"
      state: absent
      region: "{{ gcp_region }}"

- name: remove {{ instance_name }} network
  gcp_compute_network:
      name: "{{ instance_name }}-network"
      state: absent
