---
- name: check type variable
  assert:
    that:
    - type is defined
    - type == "gcp" or type == "ec2" or type == "rhv"
    fail_msg: "type has to be ec2, gcp or rhv"
    success_msg: "type is defined"

- name: check instance parameters
  assert:
    that:
    - instance_name is defined
    fail_msg: "instance_name is not defined"
    success_msg: "instance_name is defined"

- name: check instance_flavor is defined
  assert:
    that:
    - instance_flavor is defined
    fail_msg: "instance_flavor is not defined"
    success_msg: "instance_flavor is defined"

- name: create instance on GCP
  import_tasks: gcp_instance.yml
  when:
  - type == "gcp"
  - remove is not defined

- name:  remove instance on GCP
  import_tasks: gcp_remove_instance.yml
  when:
  - type == "gcp"
  - remove is defined

- name: create instance on EC2
  import_tasks: ec2_instance.yml
  when:
  - type == "ec2"
  - remove is not defined

- name:  remove instance on EC2
  import_tasks: ec2_remove_instance.yml
  when:
  - type == "ec2"
  - remove is defined

- name: create instance on RHV
  import_tasks: rhv_instance.yml
  when:
  - type == "rhv"
  - remove is not defined

- name: remove instance on RHV
  import_tasks: rhv_remove_instance.yml
  when:
  - type == "rhv"
  - remove is defined
