---
- name: log into RHV
  ovirt_auth:
    hostname: "{{ rhv_hostname }}"
    insecure: true
    username: "{{ rhv_username }}"
    password: "{{ rhv_password }}"
    state: present

- name: remove Virtual Machine
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ rhv_cluster }}"
    name: "{{ instance_name }}"
    state: absent
