---
- name: log into RHV
  ovirt_auth:
    # no credentials are needed, if environment variables are used (OVIRT_HOSTNAME, OVIRT_USERNAME, OVIRT_PASSWORD)
    insecure: true
    state: present

- name: create Disk
  ovirt_disk:
    auth: "{{ ovirt_auth }}"
    size: 20GiB
    storage_domain: "{{ rhv_storage_domain }}"
    name: "{{ instance_name }}_disk"

- name: create Virtual Machine with defined MAC address
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ rhv_cluster }}"
    name: "{{ instance_name }}"
    memory: "{{ rhv_memory }}"
    cpu_cores: "{{ rhv_cores }}"
    type: server
    boot_devices:
    - hd
    - network
    operating_system: rhel_7x64
    nics:
    - name: nic1
      profile_name: ovirtmgmt
      mac_address: "{{ instance_mac_address }}"
    disks:
    - name: "{{ instance_name }}_disk"
      bootable: true
    state: running
  when: instance_mac_address is defined

- name: create Virtual Machine
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ rhv_cluster }}"
    name: "{{ instance_name }}"
    memory: "{{ rhv_memory }}"
    cpu_cores: "{{ rhv_cores }}"
    type: server
    boot_devices:
    - hd
    - network
    operating_system: rhel_7x64
    nics:
    - name: nic1
      profile_name: ovirtmgmt
    disks:
    - name: "{{ instance_name }}_disk"
      bootable: true
    state: running
  when: instance_mac_address is not defined
